project_id = "garm-test"
zone = "us-central1-a"
network_id = "projects/garm-test/global/networks/garm"
subnetwork_id = "projects/garm-test/regions/us-central1/subnetworks/garm"
# The credentials file is optional.
# Leave this empty if you want to use the default credentials.
credentials_file = "/etc/garm/service-account-key.json"
external_ip_access = true