name: Check Equality

on: [push, pull_request]

jobs:
  check-equality:
    runs-on: ubuntu-latest
    steps:
      - name: Check if 1 equals 1
        run: |
          if [ 1 -eq 1 ]; then
            echo "1 equals 1"
          else
            echo "1 does not equal 1"
            exit 1
          fi
      - name: Test
        run: |
          ls -lah /